export const ActionType = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCT_DETAILS: "FETCH_PRODUCT_DETAILS",
};
